name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# Añadir permisos para que GitHub Actions pueda hacer push
permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: List Structure Before Build
        run: find . -type f -not -path "*/node_modules/*" -not -path "*/\.*" | sort
        
      - name: Build project
        run: npm run build
        env:
          BASE_URL: /taskflow/
        
      - name: List Build Output
        run: ls -la dist
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist 